services:
  mongo-market-data:
    image: mongo:6.0
    container_name: mongo-market-data
    restart: always
    ports:
      - "27020:27017"
    volumes:
      - ./mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-market-data:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: api-market-data
    restart: always
    env_file:
      - .env
    depends_on:
      mongo-market-data:
        condition: service_healthy
    ports:
      - "8081:8080"
    volumes:
      - .:/app:delegated
    working_dir: /app
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mongo_data:
